CREATE TABLE Beds (
BedID integer NOT NULL GENERATED ALWAYS AS IDENTITY,
BedTypeID integer NOT NULL REFERENCES BedTypes,
BedCode text NOT NULL,
UnitID integer NOT NULL REFERENCES Units,
PRIMARY KEY (BedID),
UNIQUE (UnitID, BedCode)
);
